version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=mayer
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mayer_dev
    ports:
      - '5432:5432'
